## NumPy Multidimensional Arrays

In [2]:
import numpy as np

In [6]:
array_2d = np.array([[1,2], [3, 4]])
print(array_2d)

[[1 2]
 [3 4]]


In [7]:
X = np.array([[1, 2], [3, 4]])
Y = np.array([[1, -1], [0, 1]])

In [8]:
print(Y)

[[ 1 -1]
 [ 0  1]]


In [9]:
X + Y

array([[2, 1],
       [3, 5]])

In [10]:
X * Y

array([[ 1, -2],
       [ 0,  4]])

In [11]:
X @ Y

array([[1, 1],
       [3, 1]])

In [12]:
np.dot(X, Y)

array([[1, 1],
       [3, 1]])

## Accessing Elements from 2D Array

In [13]:
X

array([[1, 2],
       [3, 4]])

In [15]:
X[0, 0]

1

In [16]:
X[0, 1]

2

In [17]:
X[0, :]

array([1, 2])

In [19]:
X[:, 0]

array([1, 3])

*syntax:*

`numpy.reshape(array, newshape)`

In [20]:
# Create an array of 24 elements staring at 0
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [21]:
a_3d = np.reshape(a, (2, 3, 4))
print(a_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [22]:
a_3d[:, :, 0]

array([[ 0,  4,  8],
       [12, 16, 20]])

## Numpy == fasle and cea

In [24]:
import random

In [50]:
numbers_1 = random.sample(range(100), 100)
numbers_2 = random.sample(range(100), 100)

In [40]:
type(numbers_1)

list

In [44]:
%%time

list_result = []
for i in range(100):
    list_result.append(numbers_1[i] + numbers_2[i])

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 42.2 µs


In [45]:
print(list_result)

[94, 94, 74, 58, 145, 132, 54, 81, 1, 108, 27, 88, 104, 100, 53, 152, 109, 84, 191, 93, 110, 88, 139, 72, 97, 81, 122, 127, 67, 155, 112, 100, 145, 161, 62, 90, 138, 68, 29, 79, 126, 118, 99, 99, 101, 99, 87, 138, 129, 118, 133, 29, 94, 120, 98, 72, 114, 141, 69, 22, 64, 66, 29, 61, 98, 49, 113, 137, 98, 158, 175, 63, 175, 119, 102, 139, 86, 137, 109, 77, 113, 163, 42, 68, 177, 131, 78, 176, 58, 195, 110, 10, 117, 119, 90, 97, 43, 41, 51, 76]


In [54]:
array_1 = np.random.randint(0, 100, size = 100)
array_2 = np.random.randint(0, 100, size = 100)
print(array_1[0:10])
print(array_2[0:10])

[80 41 12 96 31 95 76 29 34 35]
[90 16 23 54 47 42 20 34 27  3]


In [55]:
%%time

array_result = array_1 + array_2

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 17.6 µs
