In [4]:
import numpy as np

In [5]:
np.array([3, 5, 8, 17])

array([ 3,  5,  8, 17])

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.zeros(3)

array([0., 0., 0.])

*syntax:*

for `numpy.arange(start, stop, step)`

- start defaults to 0
- stop is not inclusive
- default for step is 1

In [8]:
np.arange(4)

array([0, 1, 2, 3])

In [9]:
np.arange(2, 8)

array([2, 3, 4, 5, 6, 7])

In [10]:
np.arange(2, 9, 3)

array([2, 5, 8])

In [11]:
# process: 1 + 0.6 = 1.6 and then cut into interger 1, and then 1 + 0.6 again, and then cut ...
np.arange(1, 6, .6, dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

*syntax:*

`numpy.linspace(start, stop, num)`

default for num is 50

In [12]:
np.linspace(2, 3)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [13]:
len(np.linspace(2, 3))

50

In [14]:
np.linspace(-1, 1, 9)

array([-1.  , -0.75, -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ])

## Array Operations

In [15]:
x_array = np.linspace(-1, 1, 9)

In [16]:
type(x_array)

numpy.ndarray

In [17]:
print(x_array)

[-1.   -0.75 -0.5  -0.25  0.    0.25  0.5   0.75  1.  ]


In [18]:
y_array = x_array**2
print(y_array)

[1.     0.5625 0.25   0.0625 0.     0.0625 0.25   0.5625 1.    ]


In [19]:
z_array = np.sqrt(y_array)
print(z_array)

[1.   0.75 0.5  0.25 0.   0.25 0.5  0.75 1.  ]


In [20]:
print(y_array**0.5)

[1.   0.75 0.5  0.25 0.   0.25 0.5  0.75 1.  ]


In [21]:
add_array = x_array + y_array
print(add_array)

[ 0.     -0.1875 -0.25   -0.1875  0.      0.3125  0.75    1.3125  2.    ]


In [22]:
mult_array = x_array * z_array
print(mult_array)

[-1.     -0.5625 -0.25   -0.0625  0.      0.0625  0.25    0.5625  1.    ]


In [23]:
mult_array.round(1)

array([-1. , -0.6, -0.2, -0.1,  0. ,  0.1,  0.2,  0.6,  1. ])

In [24]:
np.round(mult_array, 3)

array([-1.   , -0.562, -0.25 , -0.062,  0.   ,  0.062,  0.25 ,  0.562,
        1.   ])

In [25]:
x_array / y_array

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([-1.        , -1.33333333, -2.        , -4.        ,         nan,
        4.        ,  2.        ,  1.33333333,  1.        ])

### Exercise

In [26]:
my_array = np.arange(4, 81, 2)
print(my_array)

[ 4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50
 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80]


In [27]:
a = np.array([14, 20, 75, 90])
b = np.array([10, 32, 18, 120])

total_array = a + b
print(total_array)

[ 24  52  93 210]


In [28]:
less_array = total_array - 10
print(less_array)

[ 14  42  83 200]


In [29]:
new_array = np.array([18, 20, 3, 5, 8, 21])
print(new_array)

[18 20  3  5  8 21]


In [30]:
new_array[0]

18

In [31]:
new_array[-1]

21

In [32]:
new_array[3:6]

array([ 5,  8, 21])

### Exercise

In [37]:
scores = np.array([99, 85, 90, 75, 88])
new_scores_1 = scores + 1
print(new_scores_1)

add_scores= np.ones(len(scores), dtype = int)
new_scores_2 = scores + add_scores
print(new_scores_2)

[100  86  91  76  89]
[100  86  91  76  89]


In [38]:
for idx, score in enumerate(scores):
    scores[idx] = score + 1

print(scores)

[100  86  91  76  89]
